### ISSUE TITLE
On dashboard in 'day' mode, plot x-axis labels are difficult to read

### ISSUE THREAD

**Issue by brylie** [synw/django-chartflo-demo#2]
When viewing the dashboard in 'day' mode, the plot x-axis labels are difficult/impossible to read.

![screenshot_20180909_225530](https://user-images.githubusercontent.com/17307/45268353-9c40ad80-b483-11e8-92a4-2535f830cb64.png)

**Comment by brylie** [comment]
Is there a way to tell Bokeh to dynamically format the timeseries axis?

**Comment by synw** [comment]
For the timeline the problem was that I was formatting the dates with the month name so they were treated as categorical data: this is fixed.

For the diff timeline the problem is that the bar chart automatically consider that the data is categorical, so it can not nicely organize the date ticks. A possible workaround is to use an area with points, but this is poorest than bar charts:

![diffchartarea](https://user-images.githubusercontent.com/12034394/45291839-c37a9780-b4e2-11e8-86e8-5984946ca7eb.png)

I think that the bar chart gives the best representation here, so I want to keep it. Another workaround would be to use custom ticks, but it does not seem to be possible on categorical data yet: [ref](https://github.com/ioam/holoviews/issues/2640#issuecomment-386651892). So I went for a brutal workaround: suppress the xaxis ticks for the day chart: this is more or less ok because we still have the hover tool to read the dates on the datapoints.

This is updated. Note: you have to update Dataswim to version 0.4.21 as a few minor fixes had been done in it

**Comment by brylie** [comment]
> I think that the bar chart gives the best representation here, so I want to keep it. 

Yeah, it's kind of annoying when charting libraries don't have timeseries bar charts.

**Comment by synw** [comment]
I'll try with Altair to see what it does, now that it works with Chartflo #3

**Comment by synw** [comment]
I managed to make better charts with Altair for the day view. Timeline:

![timeline](https://user-images.githubusercontent.com/12034394/45499812-a6f19000-b76c-11e8-9490-fd19a1be4f59.png)

Diffmean timeline:

![diffmean](https://user-images.githubusercontent.com/12034394/45499844-b375e880-b76c-11e8-90a1-7836c1206014.png)

Upgrade needed to Chartflo 0.5.2 and Dataswim 0.4.23. Note I added nabvar ordering in Chartflo so a migration is needed in case of upgrade

The line and bar charts + numbers has been integrated in the Dataswim api. A timeline with numbers is as simple as:

```
# with a dataframe with columns Date and Value:
ds.chart("Date:T", "Value:Q")
chart  = ds.line_num_()
```
